In [ ]:
# KNN Classification for the cricket match win prediction
# step 1 import the modules
import pandas as pd
from pandas import read_csv
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing

import warnings
warnings.filterwarnings("ignore")
# step 2 Load the contents of the CSV file into a DataFrame

In [19]:
filename = 'sportsdataone.csv'
headernames = ['Game_number','Result','Avg_team_Age','Match_light_type','Match_format','Bowlers_in_team','Wicket_keeper_in_team','All_rounder_in_team','First_selection','Opponent','Season','Audience_number','Offshore','Max_run_scored_1over','Max_wicket_taken_1over','Extra_bowls_bowled','Min_run_given_1over','Min_run_scored_1over','Max_run_given_1over','extra_bowls_opponent','player_highest_run','Players_scored_zero','player_highest_wicket']
df = read_csv(filename, names=headernames, na_values=["NA"])
df = df.dropna()
# Swap the values of column A and B
#df[['player_highest_wicket', 'Result']] = df[['Result', 'player_highest_wicket']]
print(df)
input("press ENTER to continue: ")

     Game_number Result  Avg_team_Age Match_light_type Match_format  \
0         Game_1   Loss          18.0              Day          ODI
1         Game_2    Win          24.0              Day          T20
4         Game_5   Loss          24.0            Night          ODI
5         Game_6    Win          24.0            Night          ODI
6         Game_7   Loss          24.0    Day and Night          T20
...          ...    ...           ...              ...          ...
2925   Game_2926    Win          30.0              Day          T20
2926   Game_2927    Win          30.0              Day          ODI
2927   Game_2928    Win          30.0    Day and Night          ODI
2928   Game_2929    Win          30.0              Day          ODI
2929   Game_2930    Win          30.0              Day          ODI

      Bowlers_in_team  Wicket_keeper_in_team  All_rounder_in_team  \
0                 3.0                      1                  3.0
1                 3.0                      1                  4.0
4                 1.0                      1                  3.0
5                 3.0                      1                  4.0
6                 2.0                      1                  2.0
...               ...                    ...                  ...
2925              3.0                      1                  4.0
2926              4.0                      1                  3.0
2927              4.0                      1                  3.0
2928              4.0                      1                  3.0
2929              4.0                      1                  3.0

     First_selection      Opponent  ... Max_run_scored_1over  \
0            Bowling      Srilanka  ...                 13.0
1            Batting      Zimbabwe  ...                 12.0
4            Bowling      Srilanka  ...                 12.0
5            Batting      Srilanka  ...                 15.0
6            Batting      Zimbabwe  ...                 12.0
...              ...           ...  ...                  ...
2925         Batting  South Africa  ...                 15.0
2926         Bowling         Kenya  ...                 14.0
2927         Bowling      Pakistan  ...                 14.0
2928         Batting         Kenya  ...                 14.0
2929         Batting         Kenya  ...                 12.0

      Max_wicket_taken_1over Extra_bowls_bowled  Min_run_given_1over  \
0                          3                0.0                    2
1                          1                0.0                    0
4                          4                0.0                    0
5                          3                0.0                    5
6                          3                0.0                    0
...                      ...                ...                  ...
2925                       3                8.0                    0
2926                       4                8.0                    2
2927                       4               10.0                    2
2928                       2               20.0                    2
2929                       4                4.0                    5

      Min_run_scored_1over  Max_run_given_1over  extra_bowls_opponent  \
0                      3.0                  6.0                     0
1                      3.0                  6.0                     0
4                      3.0                  6.0                     0
5                      4.0                  6.0                     0
6                      4.0                  6.0                     0
...                    ...                  ...                   ...
2925                   3.0                  6.0                     3
2926                   3.0                  6.0                     2
2927                   4.0                 10.0                     2
2928                   3.0                  6.0                     3
2929                   3.0                  6.0                     3

      player_highest_run  Players_scored_zero  player_highest_wicket
0                   54.0                    3                      1
1                   69.0                    2                      1
4                   80.0                    3                      1
5                   97.0                    3                      1
6                   70.0                    3                      1
...                  ...                  ...                    ...
2925                50.0                    3                      2
2926                52.0                    2                      1
2927                80.0                    3                      2
2928                98.0                    3                      1
2929                62.0                    1                      1

[2258 rows x 23 columns]
press ENTER to continue:

''

In [20]:
# step 3 perform label encoding of string data

label_encoder = preprocessing.LabelEncoder()
df['Result']= label_encoder.fit_transform(df['Result'])
df['Result'].unique()

label_encoder = preprocessing.LabelEncoder()
df['Season']= label_encoder.fit_transform(df['Season'])
df['Season'].unique()

label_encoder = preprocessing.LabelEncoder()
df['Opponent']= label_encoder.fit_transform(df['Opponent'])
df['Opponent'].unique()

label_encoder = preprocessing.LabelEncoder()
df['First_selection']= label_encoder.fit_transform(df['First_selection'])
df['First_selection'].unique()

label_encoder = preprocessing.LabelEncoder()
df['Offshore']= label_encoder.fit_transform(df['Offshore'])
df['Offshore'].unique()

label_encoder = preprocessing.LabelEncoder()
df['Match_light_type']= label_encoder.fit_transform(df['Match_light_type'])
df['Match_light_type'].unique()

label_encoder = preprocessing.LabelEncoder()
df['Match_format']= label_encoder.fit_transform(df['Match_format'])
df['Match_format'].unique()

print(df)
input("press ENTER to continue: ")

     Game_number  Result  Avg_team_Age  Match_light_type  Match_format  \
0         Game_1       0          18.0                 0             1
1         Game_2       1          24.0                 0             2
4         Game_5       0          24.0                 2             1
5         Game_6       1          24.0                 2             1
6         Game_7       0          24.0                 1             2
...          ...     ...           ...               ...           ...
2925   Game_2926       1          30.0                 0             2
2926   Game_2927       1          30.0                 0             1
2927   Game_2928       1          30.0                 1             1
2928   Game_2929       1          30.0                 0             1
2929   Game_2930       1          30.0                 0             1

      Bowlers_in_team  Wicket_keeper_in_team  All_rounder_in_team  \
0                 3.0                      1                  3.0
1                 3.0                      1                  4.0
4                 1.0                      1                  3.0
5                 3.0                      1                  4.0
6                 2.0                      1                  2.0
...               ...                    ...                  ...
2925              3.0                      1                  4.0
2926              4.0                      1                  3.0
2927              4.0                      1                  3.0
2928              4.0                      1                  3.0
2929              4.0                      1                  3.0

      First_selection  Opponent  ...  Max_run_scored_1over  \
0                   2         6  ...                  13.0
1                   1         8  ...                  12.0
4                   2         6  ...                  12.0
5                   1         6  ...                  15.0
6                   1         8  ...                  12.0
...               ...       ...  ...                   ...
2925                1         5  ...                  15.0
2926                2         3  ...                  14.0
2927                2         4  ...                  14.0
2928                1         3  ...                  14.0
2929                1         3  ...                  12.0

      Max_wicket_taken_1over  Extra_bowls_bowled  Min_run_given_1over  \
0                          3                 0.0                    2
1                          1                 0.0                    0
4                          4                 0.0                    0
5                          3                 0.0                    5
6                          3                 0.0                    0
...                      ...                 ...                  ...
2925                       3                 8.0                    0
2926                       4                 8.0                    2
2927                       4                10.0                    2
2928                       2                20.0                    2
2929                       4                 4.0                    5

      Min_run_scored_1over  Max_run_given_1over  extra_bowls_opponent  \
0                      3.0                  6.0                     0
1                      3.0                  6.0                     0
4                      3.0                  6.0                     0
5                      4.0                  6.0                     0
6                      4.0                  6.0                     0
...                    ...                  ...                   ...
2925                   3.0                  6.0                     3
2926                   3.0                  6.0                     2
2927                   4.0                 10.0                     2
2928                   3.0                  6.0                     3
2929                   3.0                  6.0                     3

      player_highest_run  Players_scored_zero  player_highest_wicket
0                   54.0                    3                      1
1                   69.0                    2                      1
4                   80.0                    3                      1
5                   97.0                    3                      1
6                   70.0                    3                      1
...                  ...                  ...                    ...
2925                50.0                    3                      2
2926                52.0                    2                      1
2927                80.0                    3                      2
2928                98.0                    3                      1
2929                62.0                    1                      1

[2258 rows x 23 columns]
press ENTER to continue:

''

In [21]:

# Write the updated DataFrame back to the file
df.to_csv("file.csv")#, index=False)`

label_encoder = preprocessing.LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        # encode the non-numeric column using LabelEncoder
        df[col] = label_encoder.fit_transform(df[col])

In [22]:

# step 4 seperate the input and output

array = df.values
inputx = array[:,2:22]
outputy = array[:,1]


# step 5 choose the KNN algorithm / model for doing classification

thismodel = KNeighborsClassifier()
print("\nThe model selected is",thismodel)
print("\nThe parameters of the model are\n\n",thismodel.get_params())
#print(thismodel.set_params())


# step 6: training the model
thismodel.fit(inputx,outputy)

The model selected is KNeighborsClassifier()

The parameters of the model are

 {'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 5, 'p': 2, 'weights': 'uniform'}

KNeighborsClassifier()

In [23]:

# step 7: testing and model prediction

df_200 = df.head(200)
# Write the first 200 rows to a csv file
df_200.to_csv("sportsdataonetest.csv", index=False)
print(df_200)
input("press ENTER to continue: ")

     Game_number  Result  Avg_team_Age  Match_light_type  Match_format  \
0              0       0          18.0                 0             1
1            796       1          24.0                 0             2
4           1807       0          24.0                 2             1
5           1900       1          24.0                 2             1
6           1991       0          24.0                 1             2
..           ...     ...           ...               ...           ...
239         1126       1          25.0                 0             2
240         1133       1          25.0                 0             1
242         1151       1          25.0                 1             1
244         1167       1          25.0                 0             1
246         1183       0          26.0                 0             1

     Bowlers_in_team  Wicket_keeper_in_team  All_rounder_in_team  \
0                3.0                      1                  3.0
1                3.0                      1                  4.0
4                1.0                      1                  3.0
5                3.0                      1                  4.0
6                2.0                      1                  2.0
..               ...                    ...                  ...
239              1.0                      1                  1.0
240              3.0                      1                  1.0
242              1.0                      1                  4.0
244              1.0                      1                  4.0
246              3.0                      1                  1.0

     First_selection  Opponent  ...  Max_run_scored_1over  \
0                  2         6  ...                  13.0
1                  1         8  ...                  12.0
4                  2         6  ...                  12.0
5                  1         6  ...                  15.0
6                  1         8  ...                  12.0
..               ...       ...  ...                   ...
239                2         5  ...                  11.0
240                2         6  ...                  11.0
242                2         2  ...                  17.0
244                2         6  ...                  19.0
246                2         6  ...                  12.0

     Max_wicket_taken_1over  Extra_bowls_bowled  Min_run_given_1over  \
0                         3                 0.0                    2
1                         1                 0.0                    0
4                         4                 0.0                    0
5                         3                 0.0                    5
6                         3                 0.0                    0
..                      ...                 ...                  ...
239                       2                 6.0                    0
240                       2                 7.0                    2
242                       3                 7.0                    6
244                       3                 7.0                    2
246                       3                 1.0                    2

     Min_run_scored_1over  Max_run_given_1over  extra_bowls_opponent  \
0                     3.0                  6.0                     0
1                     3.0                  6.0                     0
4                     3.0                  6.0                     0
5                     4.0                  6.0                     0
6                     4.0                  6.0                     0
..                    ...                  ...                   ...
239                   2.0                  6.0                     2
240                   2.0                  6.0                     2
242                   3.0                  7.0                     7
244                   2.0                  6.0                     2
246                   2.0                  6.0                     0

     player_highest_run  Players_scored_zero  player_highest_wicket
0                  54.0                    2                      0
1                  69.0                    1                      0
4                  80.0                    2                      0
5                  97.0                    2                      0
6                  70.0                    2                      0
..                  ...                  ...                    ...
239                93.0                    3                      1
240                81.0                    2                      0
242                77.0                    3                      1
244                57.0                    2                      0
246                48.0                    0                      0

[200 rows x 23 columns]
press ENTER to continue:

''

In [24]:
filename = 'sportsdataonetest.csv'
headernames = ['Game_number','Result','Avg_team_Age','Match_light_type','Match_format','Bowlers_in_team','Wicket_keeper_in_team','All_rounder_in_team','First_selection','Opponent','Season','Audience_number','Offshore','Max_run_scored_1over','Max_wicket_taken_1over','Extra_bowls_bowled','Min_run_given_1over','Min_run_scored_1over','Max_run_given_1over','extra_bowls_opponent','player_highest_run','Players_scored_zero','player_highest_wicket']
newdataframe = read_csv(filename)#, names=headernames)
#newdataframe = newdataframe.dropna()
array = newdataframe.values
testinputz = array[:,2:22]
print("\n\nThe test inputs are\n\n",newdataframe)
input("press ENTER to continue: ")

The test inputs are

      Game_number  Result  Avg_team_Age  Match_light_type  Match_format  \
0              0       0          18.0                 0             1
1            796       1          24.0                 0             2
2           1807       0          24.0                 2             1
3           1900       1          24.0                 2             1
4           1991       0          24.0                 1             2
..           ...     ...           ...               ...           ...
195         1126       1          25.0                 0             2
196         1133       1          25.0                 0             1
197         1151       1          25.0                 1             1
198         1167       1          25.0                 0             1
199         1183       0          26.0                 0             1

     Bowlers_in_team  Wicket_keeper_in_team  All_rounder_in_team  \
0                3.0                      1                  3.0
1                3.0                      1                  4.0
2                1.0                      1                  3.0
3                3.0                      1                  4.0
4                2.0                      1                  2.0
..               ...                    ...                  ...
195              1.0                      1                  1.0
196              3.0                      1                  1.0
197              1.0                      1                  4.0
198              1.0                      1                  4.0
199              3.0                      1                  1.0

     First_selection  Opponent  ...  Max_run_scored_1over  \
0                  2         6  ...                  13.0
1                  1         8  ...                  12.0
2                  2         6  ...                  12.0
3                  1         6  ...                  15.0
4                  1         8  ...                  12.0
..               ...       ...  ...                   ...
195                2         5  ...                  11.0
196                2         6  ...                  11.0
197                2         2  ...                  17.0
198                2         6  ...                  19.0
199                2         6  ...                  12.0

     Max_wicket_taken_1over  Extra_bowls_bowled  Min_run_given_1over  \
0                         3                 0.0                    2
1                         1                 0.0                    0
2                         4                 0.0                    0
3                         3                 0.0                    5
4                         3                 0.0                    0
..                      ...                 ...                  ...
195                       2                 6.0                    0
196                       2                 7.0                    2
197                       3                 7.0                    6
198                       3                 7.0                    2
199                       3                 1.0                    2

     Min_run_scored_1over  Max_run_given_1over  extra_bowls_opponent  \
0                     3.0                  6.0                     0
1                     3.0                  6.0                     0
2                     3.0                  6.0                     0
3                     4.0                  6.0                     0
4                     4.0                  6.0                     0
..                    ...                  ...                   ...
195                   2.0                  6.0                     2
196                   2.0                  6.0                     2
197                   3.0                  7.0                     7
198                   2.0                  6.0                     2
199                   2.0                  6.0                     0

     player_highest_run  Players_scored_zero  player_highest_wicket
0                  54.0                    2                      0
1                  69.0                    1                      0
2                  80.0                    2                      0
3                  97.0                    2                      0
4                  70.0                    2                      0
..                  ...                  ...                    ...
195                93.0                    3                      1
196                81.0                    2                      0
197                77.0                    3                      1
198                57.0                    2                      0
199                48.0                    0                      0

[200 rows x 23 columns]
press ENTER to continue:

''

In [25]:
res=thismodel.predict(testinputz)
print(res)
input("press ENTER to continue: ")

[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1.
 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.
 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.
 0. 1. 1. 1. 1. 1. 1. 1.]
press ENTER to continue:

''

In [26]:
# step 5: visualizing the test results
reslist=[]
for val in res:
    if val==0:
        reslist.append("We Lose")
    else:
        reslist.append("We Win")
print("\nThe test results are\n\n",reslist)
input("press ENTER to continue: ")
#res=thismodel.predict(testinputz)
#print(thismodel.predict(testinputz))

The test results are

 ['We Lose', 'We Win', 'We Lose', 'We Win', 'We Lose', 'We Win', 'We Lose', 'We Win', 'We Lose', 'We Win', 'We Lose', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Lose', 'We Lose', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Lose', 'We Lose', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Lose', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Lose', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win', 'We Win']
press ENTER to continue:

''